package org.nebulaframework.discovery.ws;
//Generated by MyEclipse

public interface ColombusManager {
	public void registerCluster(String ip);
	public void unregisterCluster(String ip);
	public void registerColombusService(String ip);
	public void unregisterColombusService(String ip);
}